version: "3.7"

services:
  web:
    #image: kmdn/combining-linking-techniques
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080
    volumes:
      - ./properties:/clit/properties

