version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080
    volumes:
      - ./properties:/clit/properties
  rel:
    build:
      context: ./REL/
      dockerfile: Dockerfile
    ports:
      - 5555:5555

