version: "3.7"

services:
  web:
    image: kmdn/combining-linking-techniques
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080
  md_spacy:
    image: kmdn/clit-spacy-mention-detector
    ports:
      - 5001:5001
  linker_recommender:
    image: kmdn/clit-linker-recommender-svm
    ports:
      - 5002:5002